on:
  schedule:
    - cron: '0 0 * * 1'

jobs:
  weekly-gputests:
    strategy:
      matrix:
        branch: [master, develop, v4]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger buildkite build
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          PIPELINE: explosion-ai/spacy-gpu-test-suite
          BRANCH: ${{ matrix.branch }}
          MESSAGE: ":github: Weekly GPU tests - triggered from a GitHub Action"
        secrets:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_SECRET }}
