on:
  schedule:
    - cron: '0 0 * * *'

jobs:
  daily-slowtests:
    strategy:
      matrix:
        branch: [master, develop, v4]
    runs-on: ubuntu-latest
    steps:
      - name: Trigger buildkite build
        uses: buildkite/trigger-pipeline-action@v1.2.0
        env:
          PIPELINE: explosion-ai/spacy-slow-tests
          BRANCH: ${{ matrix.branch }}
          MESSAGE: ":github: Daily slow tests - triggered from a GitHub Action"
        secrets:
          BUILDKITE_API_ACCESS_TOKEN: ${{ secrets.BUILDKITE_SECRET }}
